# Generated by Django 5.1.5 on 2025-01-19 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('egg_photo', models.ImageField(upload_to='egg_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='EggHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_egg_harvest', models.PositiveIntegerField()),
                ('egg_photo', models.ImageField(upload_to='egg_harvest_photos/')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_harvests', to='api.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_amount', models.PositiveIntegerField()),
                ('waste_photo', models.ImageField(upload_to='waste_photos/')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='api.cycle')),
            ],
        ),
    ]
