# Generated by Django 5.1.5 on 2025-01-23 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waste',
            name='cycle',
        ),
        migrations.AddField(
            model_name='waste',
            name='waste_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(choices=[('egg', 'Fase Telur'), ('larva', 'Fase Larva'), ('prepupa', 'Fase Prepupa'), ('pupa', 'Fase Pupa'), ('bsf', 'Fase BSF'), ('harvest', 'Panen')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.cycle')),
            ],
        ),
        migrations.AddField(
            model_name='waste',
            name='phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='api.phase'),
        ),
    ]
