# Generated by Django 5.1.5 on 2025-01-23 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_waste_cycle_waste_waste_date_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LarvaHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('total_harvest', models.PositiveIntegerField()),
                ('total_for_sale', models.PositiveIntegerField()),
                ('total_for_breeding', models.PositiveIntegerField()),
                ('total_kasgot', models.PositiveIntegerField()),
                ('harvest_photo', models.ImageField(upload_to='harvest_photos/')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='larva_harvests', to='api.phase')),
            ],
        ),
    ]
