# Generated by Django 5.1.5 on 2025-01-23 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_larvaharvest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='end_date',
        ),
        migrations.AddField(
            model_name='eggharvest',
            name='harvest_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='larvaharvest',
            name='harvest_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='waste',
            name='waste_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
