# Generated by Django 5.1.5 on 2025-01-23 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_phase_end_date_eggharvest_harvest_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.phase')),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('videoId', models.CharField(max_length=100)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.phase')),
            ],
        ),
    ]
