# Generated by Django 5.1.5 on 2025-01-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_article_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='date_published',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='youtube',
            name='channel_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='youtube',
            name='date_published',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
