# Generated by Django 5.1.5 on 2025-01-25 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_article_author_article_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='api.phase'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='api.phase'),
        ),
    ]
