# Generated by Django 5.1.5 on 2025-01-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_article_phase_alter_youtube_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='description',
            field=models.TextField(default='Deskripsi video'),
        ),
    ]
