# Generated by Django 5.1.1 on 2025-03-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_notification_cycle_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
