# Generated by Django 5.1.1 on 2025-03-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_phase_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='points',
        ),
        migrations.AddField(
            model_name='cycle',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
