# Generated by Django 5.1.1 on 2025-03-02 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_phase_points_cycle_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cycle'),
        ),
        migrations.AddField(
            model_name='notification',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.phase'),
        ),
    ]
