# Generated by Django 5.1.5 on 2025-02-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
