# Generated by Django 5.1.1 on 2025-02-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_points'),
        ('authentication', '0003_alter_passwordresetotp_expires_at'),
    ]

    operations = [
    ]
