# Generated by Django 5.1.1 on 2025-02-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_merge_20250222_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pics',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_harvest',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_waste',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
