# Generated by Django 5.1.1 on 2025-03-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_profile_pics_customuser_total_harvest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_harvest',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_waste',
            field=models.BigIntegerField(default=0),
        ),
    ]
